services:

  backend:
    build: .
    container_name: customer_segmentation_api

    volumes:
      - ./artifacts:/app/artifacts

    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8000

    ports:
      - "8000:8000"

    restart: unless-stopped


  frontend:
    build: .
    container_name: customer_segmentation_ui

    environment:
      API_URL: http://backend:8000/predict

    volumes:
      - ./artifacts:/app/artifacts

    command: >
      streamlit run Homepage.py
      --server.address=0.0.0.0
      --server.port=8501
      --browser.gatherUsageStats=false

    ports:
      - "8501:8501"

    depends_on:
      - backend

    restart: unless-stopped