categorical_columns:
  - Education
  - Marital_Status
  - Age_Group
  - Income_Group

numerical_columns:
  - Income
  - Recency
  - Wines
  - Fruits
  - Meat
  - Fish
  - Sweets
  - Gold
  - Deal_Purchases
  - Web_Purchases
  - Catalog_Purchases
  - Store_Purchases
  - NumWebVisitsMonth
  - AcceptedCmp3
  - AcceptedCmp4
  - AcceptedCmp5
  - AcceptedCmp1
  - AcceptedCmp2
  - Complain
  - Age
  - Children
  - Has_Partner
  - Family_Size
  - Is_Parent
  - Total_Spending
  - Spend_Ratio
  - Total_Promo_Accepted
  - Any_Promo_Accepted
  - Total_Purchases
  - Days_as_Customer
  - Year_Joined

target_column: Response

drop_columns:
  - Dt_Customer

model_features:
  - Income
  - Total_Spending
  - Total_Purchases
  - Recency
  - NumWebVisitsMonth
  - Total_Promo_Accepted
  - Children